DataPasien/urls.py
from django.urls import path

from . import views

app_name = 'DataPasien'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('listofpasien/', views.listofpasien, name='listofpasien'),
    path('edit/<str:pk>/', views.edit, name='update'),
    path('delete/<str:pk>/', views.hapus, name='delete'),
    path('sembuh/<str:pk>/', views.tambahsembuh, name='sembuh'),
    path('meninggal/<str:pk>/', views.tambahmeninggal, name='meninggal'),
    path('counter/', views.counter, name='counter'),

    
]

TK_1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pengumuman.urls')),
    path('', include('main.urls')),
    path('', include('DataPasien.urls')),
    path('', include('forum.urls')),
    path('',include('info.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

DataPasien/models.py
from django.db import models

# Create your models here.
class Pasien(models.Model):
    nama = models.CharField(max_length=100)
    umur = models.PositiveIntegerField(default=0)
    alamat = models.TextField()
    status = models.CharField('Status Covid',max_length=30,choices=(('Positif','Positif'),('Negatif','Negatif')))
    def __str__(self):
        return self.nama.title()

class Sembuh(models.Model):
    jml = models.IntegerField()
    

class Meninggal(models.Model):
    jml = models.IntegerField()

DataPasien/forms.py
from django import forms
from .models import Pasien

class Patient(forms.ModelForm):
    class  Meta:
        model = Pasien
        fields = ('nama','umur','alamat','status',)

DataPasien/views.py
from django.shortcuts import render, redirect
from .forms import Patient
from .models import Pasien, Sembuh, Meninggal

# Create your views here.

def add(request):
    form = Patient()
    if request.method == 'POST':
        form = Patient(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/listofpasien/')
    return render(request, 'DataPasien/add.html', {'form':form})


def hapus(request, pk):
    yangdiapus = Pasien.objects.get(id=pk)
    if request.method == 'POST':
        yangdiapus.delete()
        return redirect('/listofpasien/')
    return render(request, 'DataPasien/hapus.html', {'yangdiapus':yangdiapus})


def edit(request, pk):
    yangdiedit = Pasien.objects.get(id=pk)
    form = Patient(instance=yangdiedit)
    
    if request.method == 'POST':

        form = Patient(request.POST, instance=yangdiedit)

        if form.is_valid():
            form.save()
            return redirect('/listofpasien/')

    return render(request, 'DataPasien/edit.html', {'form':form })



def listofpasien(request):
    pasien2 = Pasien.objects.all()
    return render(request, 'DataPasien/listofpasien.html', {'pasien2':pasien2})

def counter(request):
    jmlsembuh = Sembuh.objects.all().count()
    jumlmeninggal = Meninggal.objects.all().count()
    pasienpos = Pasien.objects.filter(status='Positif').count()
    return render (request, 'DataPasien/counter.html', {'sembuh':jmlsembuh,'positif':pasienpos,'meninggal':jumlmeninggal})

def tambahsembuh(request, pk):
    yangsembuh = Pasien.objects.get(id=pk)
    if yangsembuh.status == 'Negatif':
        return redirect('/listofpasien/')
    if request.method == 'POST':
        Sembuh.objects.create(jml=1)
        yangsembuh.status = 'Negatif'
        return redirect('/listofpasien/')
    return render(request, 'DataPasien/sembuh.html', {'yangdiapus':yangsembuh})

def tambahmeninggal(request, pk):
    yangmeninggal = Pasien.objects.get(id=pk)
    if yangmeninggal.status == 'Negatif':
        return redirect('/listofpasien/')
    if request.method == 'POST':
        Meninggal.objects.create(jml=1)
        yangmeninggal.delete()
        return redirect('/listofpasien/')
    return render(request, 'DataPasien/meninggal.html', {'yangdiapus':yangmeninggal})

DataPasien/templates/DataPasien/add.html
{% extends 'base.html' %}

{% load static %}
{% block meta %}
<title>Tambah Pasien</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <h2 style="text-align: center; padding: 20px 0px 20px; text-shadow: 1px 1px 2px #dfdfdf;">Add Patient</h2>
</div>
    <div  style="margin: auto; margin-top: 20px;" class="d-flex justify-content-center">
        <form method="post" style="padding: 20px; background-color: rgb(255, 198, 206);" class="rounded shadow">
            {% csrf_token %}
            <table>
            {% for field in form %}
            <div class="fieldWrapper">
                    <tr>
                        <td>{{ field.errors }}
                            {{ field.label_tag }}</td>
                        <td>{{ field }}</td>
                    </tr>
            </div>
            {% endfor %}
            </table>
            <div style="padding-top: 10px;">
                <input type="submit" value ="Submit">
            </div>
        </form>
    </div>
    
{% endblock %}

DataPasien/templates/DataPasien/counter.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Stats</title>
{% endblock meta %}

{% block content%}

<div class="container" style="text-align: center; padding: 20px 0px 20px;"><h2>Analitik Rumah Sakit</h2></div>
<div class="col-lg-12 col-md-6 d-flex justify-content-around counter" style="padding: 100px 60px 100px;">
	<div class='rounded shadow' style="background-color: rgb(232, 255, 211); padding: 50px">
            Sembuh: {{sembuh}}
    </div>
	<div class='rounded shadow' style="background-color: rgb(255, 89, 89); padding: 50px">
        Positif: {{positif}}
    </div>
	<div class='rounded shadow' style="background-color: rgb(173, 173, 173); padding: 50px">
        Meninggal: {{meninggal}}
    </div>
</div>
<div class="container">
    <iframe src="https://public.domo.com/cards/bWxVg" width="100%" height="600" marginheight="0" marginwidth="0" frameborder="0"></iframe>
</div>
    
    
{% endblock %}

DataPasien/templates/DataPasien/edit.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Edit Pasien</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <h2 style="text-align: center; padding: 20px 0px 20px; text-shadow: 1px 1px 2px #dfdfdf;">Edit Patient</h2>
</div>
    <div  style="margin: auto; margin-top: 20px;" class="d-flex justify-content-center">
        <form method="post" style="padding: 20px; background-color: rgb(255, 198, 206);" class="rounded shadow">
            {% csrf_token %}
            <table>
            {% for field in form %}
            <div class="fieldWrapper">
                    <tr>
                        <td>{{ field.errors }}
                            {{ field.label_tag }}</td>
                        <td>{{ field }}</td>
                    </tr>
            </div>
            {% endfor %}
            </table>
            <div style="padding-top: 10px;">
                <input type="submit" value ="Submit">
            </div>
        </form>
    </div>
    
{% endblock %}

DataPasien/templates/DataPasien/hapus.html
{% extends 'base.html' %}
{% load static %}


{% block content%}

<br>
<div class="row justify-content-center">
	<div class="col-md-6">
		<div class="card card-body shadow">


			<p>Are you sure you want to delete "{{yangdiapus.nama}}"?</p>

			<form action="{% url 'DataPasien:delete' yangdiapus.id  %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'DataPasien:listofpasien' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm">
			</form>
		</div>
	</div>
</div>
    
    
{% endblock %}

DataPasien/templates/DataPasien/listofpasien.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>List Pasien</title>
{% endblock meta %}

{% block content%}

    <div class="col-lg-12 col-md-6">
        <h2><P style="text-align: center;padding: 20px 0px 20px;">Daftar Pasien</P></H2>
    </div>
    {% if pasien2 %}
    <div class="col">
            <table class="table table-sm daftarpas shadow">
                <tr>
                    <th>Nama</th>
                    <th>Umur</th>
                    <th>Alamat</th>
                    <th>Status Covid</th>
                    <th>Update</th>
                    <th>Remove</th>
                    <th>Sembuh</th>
                    <th>Meninggal</th>
                </tr>

                {% for pasien in pasien2 %}
                    <tr>
                        <td>{{pasien.nama}}</td>
                        <td>{{pasien.umur}}</td>
                        <td>{{pasien.alamat}}</td>
                        <td>{{pasien.status}}</td>
                        <td><a style= 'background-color: #CE3F3F; color: white;' class="btn btn-sm" href="{% url 'DataPasien:update' pasien.id %}">Update</a></td>
                        <td><a style= 'background-color: #820B0B; color: white;' class="btn btn-sm" href="{% url 'DataPasien:delete' pasien.id %}">Delete</a></td>
                        <td><a style= 'background-color: rgb(131, 212, 131); color: white;' class="btn btn-sm" href="{% url 'DataPasien:sembuh' pasien.id %}">Sembuh</a></td>
                        <td><a style= 'background-color: #2c1313; color: white;' class="btn btn-sm" href="{% url 'DataPasien:meninggal' pasien.id %}">Meninggal</a></td>

                    </tr>
                {% endfor %}


            </table>
        
    </div>
    {% else %}
    <div class="container">
        <h2 class="border shadow rounded" style="padding:10px; text-align: center;">Tidak ada data pasien.</h2>
    </div>
    {% endif %}
{% endblock %}

DataPasien/templates/DataPasien/meninggal.html
{% extends 'base.html' %}
{% load static %}


{% block content%}

<br>
<div class="row justify-content-center">
	<div class="col-md-6">
		<div class="card card-body shadow">


			<p>Are you sure you want to delete? "{{yangdiapus.nama}}"?</p>

			<form action="{% url 'DataPasien:meninggal' yangdiapus.id  %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'DataPasien:listofpasien' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm">
			</form>
		</div>
	</div>
</div>
    
    
{% endblock %}

DataPasien/templates/DataPasien/sembuh.html
{% extends 'base.html' %}
{% load static %}


{% block content%}

<br>
<div class="row justify-content-center">
	<div class="col-md-6">
		<div class="card card-body shadow">


			<p>Are you sure you want to change status to negative? "{{yangdiapus.nama}}"?</p>

			<form action="{% url 'DataPasien:sembuh' yangdiapus.id  %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'DataPasien:listofpasien' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm">
			</form>
		</div>
	</div>
</div>
    
    
{% endblock %}