TK_1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pengumuman.urls')),
    path('', include('main.urls')),
    path('', include('DataPasien.urls')),
    path('', include('forum.urls')),
    path('',include('info.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path

from .views import forum,addpost,komen,addkomen, hapuskomen, hapuspost

app_name = 'forum'

urlpatterns = [
    path('forum', forum, name='forum'),
    path('addpost', addpost, name='addpost'),
    path('comment/<int:id>',komen,name='comment'),
    path('addcomment/<int:id>',addkomen,name='addkomen'),
    path('hapuskomen/<int:id>',hapuskomen,name='hapuskomen'),
    path('hapuspost/<int:id>',hapuspost,name='hapuspost'),
]

forum/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class Post(models.Model):
    nama = models.CharField(max_length=30,default="Anonymous")
    judul = models.CharField(max_length=90)
    pesan = models.TextField(max_length=280)
    tanggal_post = models.DateTimeField(default=timezone.now)
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    nama = models.CharField(max_length=30)
    komentar = models.TextField(max_length=280)
    tanggal_komen = models.DateTimeField(default=timezone.now)

forum/forms.py
from django import forms
from .models import Post, Comment


class Form_Post(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['nama','judul','pesan']
        widgets = {
            'nama': forms.TextInput(attrs={'class':'form-control','placeholder':'Nama'}),
            'judul': forms.TextInput(attrs={'class':'form-control','placeholder':'Judul'}),
            'pesan': forms.Textarea(attrs={'class':'form-control','placeholder':'Pesan'}),
        }
        
class Form_Comment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['nama','komentar']
        widgets = {
            'nama': forms.TextInput(attrs={'class':'form-control','placeholder':'Nama'}),
            'komentar': forms.Textarea(attrs={'class':'form-control','placeholder':'Komentar'}),
        }
        

forum/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post,Comment
from .forms import Form_Post, Form_Comment

# Create your views here.
def forum(request):
    post = Post.objects.all()
    return render (request,'forum.html',{'post':post})

def addpost(request):
    if request.method == "POST":
        form = Form_Post(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect ('/forum')
        else:
            return HttpResponseRedirect('Data tidak Valid')

    form = Form_Post()
    tipe = 'Post'
    tipe2= 'Forum'
    return render(request,'add.html',{'form':form, 'tipe':tipe, 'tipe2':tipe2})

def komen(request,id):
    post = Post.objects.get(id=id)
    komen = Comment.objects.filter(post=post)
    
    return render(request,'detail.html',{'post':post,'komen':komen})
    

def addkomen(request,id):
    post = Post.objects.get(id=id)
    komen = Comment.objects.filter(post=post)
    form = Form_Comment()
    tipe = 'Comment'
    tipe2= 'The Post'
    if request.method == "POST":
        form = Form_Comment(request.POST)
        if form.is_valid():
            komen = form.save(commit=False)
            komen.post = post
            komen.save()
            return HttpResponseRedirect ('/comment/'+ str(post.id))
        else:
            return HttpResponseRedirect('Data tidak Valid')
    
    return render(request,'add.html',{'form':form,'tipe':tipe, 'tipe2':tipe2})

def hapuspost(request,id):
	post = Post.objects.get(id=id)
	post.delete()
	return HttpResponseRedirect('/forum')

def hapuskomen(request,id):
	komen = Comment.objects.get(id=id)
	komen.delete()
	return HttpResponseRedirect('/comment/'+str(komen.post.id))

forum/templates/add.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Add {{tipe}} to {{tipe2}}</title>
<link rel="stylesheet" href="{% static 'css/css.css' %}">

<style>
     body{
        font-family: 'Montserrat', sans-serif;
        background-image: url("../../static/css/obat.png");
        background-position: left;
        background-repeat: no-repeat;
        background-size: 120vh 130vh;
    }



</style>
{% endblock meta %}

{% block content %}
<div class="container-fluid">
    <div class="row" style="margin: auto;">
        <div class="col-md-4 col-md-offset-4" style="margin: auto;">
            <br>
            <h3 style="color: #CF2B2B"> Add {{tipe}} to {{tipe2}}</h3>
            <br>
            <div class="form-group">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-secondary" type="submit" value="Submit">
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

forum/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/css.css' %}">
<title>Postingan</title>
<style>
    h4{
        background-color: #CF2B2B;
        text-align: center;
        font-weight: bold;
    } 
    h3{
        color: #CF2B2B;
    }
</style>
{% endblock meta %}

{% block content %}
<div class="container-fluid">
    <br><br>
    <h4>Post</h4><br>
    {% if post %}
        <div class="list-group">
            <div class= class="list-group-item list-group-item-action">
                <small>{{post.tanggal_post}}</small><br>
                <h5>{{post.nama}}</h5><br>
            <div class="d-flex w-100 justify-content-between">
                <h3 class="mb-1">{{post.judul}}</h3>
            </div>
            <h2 style = "word-break: normal; ">{{post.pesan}} </h2>
        </div>
        </div>
    
        
    {% endif %}
    <br><br>
    <h4>Comments</h4>
    {% if komen %}
        {% for k in komen %}
            <br>
            <div class="list-group">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{k.nama}}</h5>
                    <small>{{k.tanggal_komen}}</small>
                </div>
                <p id="komentar" class="mb-1" >{{k.komentar}} </p>
                <small><a href="{% url 'forum:hapuskomen' k.id %}" style="color: black;">Hapus Komentar</a></small>
            </div>
            
        {% endfor %}
    {% else %}
        <p> Tidak ada komentar dalam post ini.</p>
    {% endif %}
    <hr>
    <a href="{% url 'forum:addkomen' post.id %}" class="btn btn-secondary btn-lg">Add New Comment</a>
            
    <hr>
</div>




{% endblock content %}

forum/templates/forum.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/css.css' %}">
<title>Forum</title>
{% endblock meta %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h3 class="display-4" style="color:#CF2B2B; font-weight: bold;">Forum</h3>
    </div>
</div>
<div class="container-fluid">
    
    <a href="{% url 'forum:addpost' %}" class="btn btn-secondary btn-lg btn-block" style="background-color: #CF2B2B; color: white; font-weight: bold;">Add New Post</a>
    <hr>
    {% if post %}
        {% for pp in post %}
        <div class="list-group">
            <a href="{% url 'forum:comment' pp.id %}" class="list-group-item list-group-item-action" style="background-color: #96908cb6; color: white; border-radius: 10px;">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{pp.nama}}</h5>
                <small>{{pp.tanggal_post}}</small>
            </div>
            <p class="mb-1" style = "word-break: normal; ">{{pp.judul}} </p>
            <p class="mb-1" style = "word-break: normal; ">{{pp.pesan}} </p>
            <small><a href="{% url 'forum:hapuspost' pp.id %}" style="color: black;"> Hapus Postingan</a></small>
            </a>
            <br>
        </div>
        {% endfor %}
    {% else %}
        <p> Tidak ada postingan di dalam forum ini.</p>
    {% endif %}

</div>

{% endblock content %}